# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hotel-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hotel-app
	pod 'SwiftGen', '~> 6.6.2'

  target 'hotel-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hotel-appUITests' do
    # Pods for testing
  end

end
